# Generated by Django 6.0.5 on 2026-06-25 18:07

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_rbac_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_rolepermission',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_userpermission',
            },
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='assigned', max_length=50)),
            ],
            options={
                'db_table': 'accounts_userregion',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200)),
                ('device_name', models.CharField(blank=True, default='', max_length=200)),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_deviceregistration',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_permission',
                'ordering': ['module', 'codename'],
                'indexes': [models.Index(fields=['module'], name='idx_perm_module')],
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenBlacklist',
            fields=[
                ('jti', models.UUIDField(primary_key=True, serialize=False)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_refreshtokenblacklist',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.region')),
            ],
            options={
                'db_table': 'accounts_region',
                'ordering': ['state', 'district', 'taluka'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_preset', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_role',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_role_active')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='primary_role',
            field=models.ForeignKey(blank=True, db_column='primary_role_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['primary_role'], name='idx_user_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['reporting_to'], name='idx_user_reporting'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state'], name='idx_user_state'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['districts'], name='idx_user_districts'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_users', to='accounts.region'),
        ),
        migrations.AddField(
            model_name='userregion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['user'], name='idx_device_user'),
        ),
        migrations.AddConstraint(
            model_name='deviceregistration',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device'),
        ),
        migrations.AddIndex(
            model_name='refreshtokenblacklist',
            index=models.Index(fields=['user'], name='idx_blacklist_user'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['state'], name='idx_region_state'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['parent'], name='idx_region_parent'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='idx_roleperm_role'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='idx_roleperm_perm'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user'], name='idx_userperm_user'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='idx_userperm_expires'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='uniq_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['allow', 'deny'])), name='ck_userperm_effect'),
        ),
        migrations.AddIndex(
            model_name='userregion',
            index=models.Index(fields=['user'], name='idx_userregion_user'),
        ),
        migrations.AddIndex(
            model_name='userregion',
            index=models.Index(fields=['region'], name='idx_userregion_region'),
        ),
        migrations.AddConstraint(
            model_name='userregion',
            constraint=models.UniqueConstraint(fields=('user', 'region'), name='uniq_user_region'),
        ),
    ]
