# Generated by Django 6.0.5 on 2026-06-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rbac_schema_gaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='taluka',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
