# Generated by Django 6.0.5 on 2026-06-26 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_align_region_district_taluka_nonnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(default='full', max_length=20)),
                ('status', models.CharField(default='success', max_length=20)),
                ('records_pushed', models.IntegerField(default=0)),
                ('records_pulled', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('sync_batch_id', models.UUIDField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='accounts.deviceregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_devicesynclog',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['device'], name='idx_synclog_device'), models.Index(fields=['user'], name='idx_synclog_user'), models.Index(fields=['-synced_at'], name='idx_synclog_synced')],
            },
        ),
    ]
