# Generated by Django 6.0.5 on 2026-06-07 08:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('village_name', models.CharField(max_length=200)),
                ('block_name', models.CharField(max_length=200)),
                ('district_name', models.CharField(max_length=200)),
                ('total_land_acre', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('crop_name', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('crop_stage', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post Harvest')], max_length=20)),
                ('crop_stage_days', models.PositiveSmallIntegerField()),
                ('demo_date', models.DateField()),
                ('product_name', models.CharField(max_length=200)),
                ('dose', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dose_unit', models.CharField(choices=[('ml/acre', 'ml/acre'), ('gm/acre', 'gm/acre'), ('kg/acre', 'kg/acre'), ('lt/acre', 'lt/acre'), ('kg/ha', 'kg/ha')], max_length=20)),
                ('demo_result', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('no_effect', 'No Effect')], max_length=20)),
                ('additional_observations', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('is_synced', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_demos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Demo',
                'verbose_name_plural': 'Product Demos',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='demo_photos/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('before', 'Before Demo'), ('after', 'After Demo')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product_demo.productdemo')),
            ],
            options={
                'ordering': ['photo_type', 'uploaded_at'],
            },
        ),
    ]
