# Generated by Django 6.0.5 on 2026-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_demo', '0005_productdemo_uniq_productdemo_executive_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdemo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
