from datetime import date

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.contrib.gis.geos import Point

from product_demo.models import ProductDemo

User = get_user_model()

DEMO_DATA = [
    # Guntur, Andhra Pradesh
    {
        'local_id': 'demo-seed-8800000001',
        'farmer_name': 'Anil Reddy', 'mobile_number': '8800000001',
        'village_name': 'Bapatla', 'block_name': 'Bapatla', 'district_name': 'Guntur',
        'total_land_acre': 5.0, 'latitude': 15.9048, 'longitude': 80.4685,
        'crop_name': 'Chilli', 'variety': 'Teja', 'crop_stage': 'fruiting', 'crop_stage_days': 65,
        'demo_date': date(2026, 2, 10), 'product_name': 'Reaper',
        'dose': 200, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Pest pressure reduced after application',
        'remark': 'Farmer satisfied with result',
    },
    {
        'local_id': 'demo-seed-8800000002',
        'farmer_name': 'Swapna Lakshmi', 'mobile_number': '8800000002',
        'village_name': 'Repalle', 'block_name': 'Repalle', 'district_name': 'Guntur',
        'total_land_acre': 8.0, 'latitude': 16.0210, 'longitude': 80.8240,
        'crop_name': 'Cotton', 'variety': 'Bunny BT', 'crop_stage': 'flowering', 'crop_stage_days': 80,
        'demo_date': date(2026, 1, 22), 'product_name': 'Avenger',
        'dose': 300, 'dose_unit': 'ml/acre',
        'demo_result': 'excellent', 'demo_phase': 'completed',
        'additional_observations': 'Whitefly infestation controlled effectively',
        'remark': 'Will recommend to neighbouring farmers',
    },
    {
        'local_id': 'demo-seed-8800000003',
        'farmer_name': 'Sridhar Varma', 'mobile_number': '8800000003',
        'village_name': 'Chilakaluripet', 'block_name': 'Chilakaluripet', 'district_name': 'Guntur',
        'total_land_acre': 4.5, 'latitude': 16.0912, 'longitude': 80.1672,
        'crop_name': 'Chilli', 'variety': 'LCA 334', 'crop_stage': 'vegetative', 'crop_stage_days': 40,
        'demo_date': date(2026, 1, 8), 'product_name': 'Guardian Gold',
        'dose': 250, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Leaf curl symptoms reduced within a week',
        'remark': 'Early intervention showed results',
    },
    {
        'local_id': 'demo-seed-8800000004',
        'farmer_name': 'Padma Rao', 'mobile_number': '8800000004',
        'village_name': 'Tenali', 'block_name': 'Tenali', 'district_name': 'Guntur',
        'total_land_acre': 6.0, 'latitude': 16.2429, 'longitude': 80.6409,
        'crop_name': 'Maize', 'variety': 'DKC 9144', 'crop_stage': 'vegetative', 'crop_stage_days': 25,
        'demo_date': date(2026, 3, 1), 'product_name': 'TOTAL',
        'dose': 400, 'dose_unit': 'gm/acre',
        'demo_result': 'average', 'demo_phase': 'completed',
        'additional_observations': 'Some re-emergence noted after 12 days',
        'remark': 'Second application may be needed',
    },
    {
        'local_id': 'demo-seed-8800000005',
        'farmer_name': 'Krishna Naidu', 'mobile_number': '8800000005',
        'village_name': 'Narasaraopet', 'block_name': 'Narasaraopet', 'district_name': 'Guntur',
        'total_land_acre': 10.0, 'latitude': 16.2355, 'longitude': 80.0490,
        'crop_name': 'Cotton', 'variety': 'RCH 2 BG II', 'crop_stage': 'fruiting', 'crop_stage_days': 90,
        'demo_date': date(2026, 2, 18), 'product_name': 'Stinger',
        'dose': 175, 'dose_unit': 'ml/acre',
        'demo_result': 'excellent', 'demo_phase': 'completed',
        'additional_observations': 'Boll weevil damage dropped significantly',
        'remark': 'Repeat order placed by farmer',
    },
    # Indore, Madhya Pradesh
    {
        'local_id': 'demo-seed-8800000006',
        'farmer_name': 'Dinesh Patidar', 'mobile_number': '8800000006',
        'village_name': 'Rajendra Nagar', 'block_name': 'Indore', 'district_name': 'Indore',
        'total_land_acre': 7.5, 'latitude': 22.7196, 'longitude': 75.8577,
        'crop_name': 'Soybean', 'variety': 'JS 9560', 'crop_stage': 'flowering', 'crop_stage_days': 55,
        'demo_date': date(2025, 8, 20), 'product_name': 'Mania',
        'dose': 500, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Stem fly incidence reduced',
        'remark': 'Farmer noted healthier pod set',
    },
    {
        'local_id': 'demo-seed-8800000007',
        'farmer_name': 'Sunita Chouhan', 'mobile_number': '8800000007',
        'village_name': 'Palda', 'block_name': 'Indore', 'district_name': 'Indore',
        'total_land_acre': 5.0, 'latitude': 22.6814, 'longitude': 75.8682,
        'crop_name': 'Wheat', 'variety': 'MP 3288', 'crop_stage': 'vegetative', 'crop_stage_days': 30,
        'demo_date': date(2025, 12, 18), 'product_name': 'Narvi',
        'dose': 300, 'dose_unit': 'gm/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Powdery mildew controlled at early stage',
        'remark': 'Preventive application worked well',
    },
    {
        'local_id': 'demo-seed-8800000008',
        'farmer_name': 'Mahesh Verma', 'mobile_number': '8800000008',
        'village_name': 'Simrol', 'block_name': 'Mhow', 'district_name': 'Indore',
        'total_land_acre': 9.0, 'latitude': 22.4830, 'longitude': 75.8920,
        'crop_name': 'Soybean', 'variety': 'MACS 1188', 'crop_stage': 'harvesting', 'crop_stage_days': 100,
        'demo_date': date(2025, 9, 15), 'product_name': 'Proton',
        'dose': 250, 'dose_unit': 'ml/acre',
        'demo_result': 'average', 'demo_phase': 'completed',
        'additional_observations': 'Results moderate, late application may have reduced efficacy',
        'remark': 'Advised earlier next season',
    },
    {
        'local_id': 'demo-seed-8800000009',
        'farmer_name': 'Geeta Rathore', 'mobile_number': '8800000009',
        'village_name': 'Betma', 'block_name': 'Depalpur', 'district_name': 'Indore',
        'total_land_acre': 4.0, 'latitude': 22.7920, 'longitude': 75.6440,
        'crop_name': 'Onion', 'variety': 'N-2-4-1', 'crop_stage': 'vegetative', 'crop_stage_days': 35,
        'demo_date': date(2026, 1, 12), 'product_name': 'Neo Super',
        'dose': 350, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Thrips population declined after first spray',
        'remark': 'Farmer repeated application after 15 days',
    },
    {
        'local_id': 'demo-seed-8800000010',
        'farmer_name': 'Rajendra Bhatt', 'mobile_number': '8800000010',
        'village_name': 'Manpur', 'block_name': 'Mhow', 'district_name': 'Indore',
        'total_land_acre': 6.5, 'latitude': 22.5290, 'longitude': 75.7140,
        'crop_name': 'Wheat', 'variety': 'GW 322', 'crop_stage': 'flowering', 'crop_stage_days': 60,
        'demo_date': date(2026, 1, 28), 'product_name': 'Torpedo',
        'dose': 400, 'dose_unit': 'ml/acre',
        'demo_result': 'excellent', 'demo_phase': 'completed',
        'additional_observations': 'Aphid control outstanding within 3 days',
        'remark': 'One of the best results in the block',
    },
    # Nagpur, Maharashtra
    {
        'local_id': 'demo-seed-8800000011',
        'farmer_name': 'Suresh Bhoyar', 'mobile_number': '8800000011',
        'village_name': 'Kalmeshwar', 'block_name': 'Kalmeshwar', 'district_name': 'Nagpur',
        'total_land_acre': 12.0, 'latitude': 21.2242, 'longitude': 78.9095,
        'crop_name': 'Cotton', 'variety': 'Nuziveedu Brahma', 'crop_stage': 'fruiting', 'crop_stage_days': 85,
        'demo_date': date(2025, 9, 22), 'product_name': 'Samurai',
        'dose': 200, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Pink bollworm pressure reduced',
        'remark': 'Farmer applied on second plot as well',
    },
    {
        'local_id': 'demo-seed-8800000012',
        'farmer_name': 'Anita Gawande', 'mobile_number': '8800000012',
        'village_name': 'Butibori', 'block_name': 'Hingna', 'district_name': 'Nagpur',
        'total_land_acre': 7.0, 'latitude': 21.0110, 'longitude': 79.0670,
        'crop_name': 'Soybean', 'variety': 'JS 335', 'crop_stage': 'flowering', 'crop_stage_days': 50,
        'demo_date': date(2025, 8, 5), 'product_name': 'Armet',
        'dose': 300, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Yellow mosaic virus not spread after treatment',
        'remark': 'Good outcome despite excess rain',
    },
    {
        'local_id': 'demo-seed-8800000013',
        'farmer_name': 'Vinod Sontakke', 'mobile_number': '8800000013',
        'village_name': 'Saoner', 'block_name': 'Saoner', 'district_name': 'Nagpur',
        'total_land_acre': 8.5, 'latitude': 21.3770, 'longitude': 78.9250,
        'crop_name': 'Orange', 'variety': 'Khasi Mandarin', 'crop_stage': 'fruiting', 'crop_stage_days': 120,
        'demo_date': date(2026, 3, 10), 'product_name': 'FPS Boron',
        'dose': 400, 'dose_unit': 'gm/acre',
        'demo_result': 'excellent', 'demo_phase': 'completed',
        'additional_observations': 'Fruit size and colour improved noticeably',
        'remark': 'Micronutrient deficiency corrected',
    },
    {
        'local_id': 'demo-seed-8800000014',
        'farmer_name': 'Priya Kolhe', 'mobile_number': '8800000014',
        'village_name': 'Narkhed', 'block_name': 'Narkhed', 'district_name': 'Nagpur',
        'total_land_acre': 5.5, 'latitude': 21.4480, 'longitude': 78.5770,
        'crop_name': 'Cotton', 'variety': 'Ajeet 199', 'crop_stage': 'vegetative', 'crop_stage_days': 45,
        'demo_date': date(2025, 8, 28), 'product_name': 'Aster',
        'dose': 250, 'dose_unit': 'ml/acre',
        'demo_result': 'average', 'demo_phase': 'completed',
        'additional_observations': 'Thrips partially controlled; second dose needed',
        'remark': 'Early boll shedding observed before treatment',
    },
    {
        'local_id': 'demo-seed-8800000015',
        'farmer_name': 'Ganesh Ingle', 'mobile_number': '8800000015',
        'village_name': 'Ramtek', 'block_name': 'Ramtek', 'district_name': 'Nagpur',
        'total_land_acre': 6.0, 'latitude': 21.3946, 'longitude': 79.3177,
        'crop_name': 'Turmeric', 'variety': 'Rajapuri', 'crop_stage': 'vegetative', 'crop_stage_days': 60,
        'demo_date': date(2025, 8, 12), 'product_name': 'FPS Zinc',
        'dose': 500, 'dose_unit': 'gm/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Leaf yellowing resolved after Zinc application',
        'remark': 'Deficiency confirmed by soil test',
    },
    # Nanded, Maharashtra
    {
        'local_id': 'demo-seed-8800000016',
        'farmer_name': 'Balaji Shinde', 'mobile_number': '8800000016',
        'village_name': 'Deglur', 'block_name': 'Deglur', 'district_name': 'Nanded',
        'total_land_acre': 11.0, 'latitude': 17.8920, 'longitude': 77.5560,
        'crop_name': 'Cotton', 'variety': 'RCH 650 BG II', 'crop_stage': 'harvesting', 'crop_stage_days': 110,
        'demo_date': date(2025, 11, 5), 'product_name': 'Plutus 58',
        'dose': 600, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Sucking pest complex well managed',
        'remark': 'Farmer plans full plot application next season',
    },
    {
        'local_id': 'demo-seed-8800000017',
        'farmer_name': 'Meena Pawar', 'mobile_number': '8800000017',
        'village_name': 'Naigaon', 'block_name': 'Naigaon', 'district_name': 'Nanded',
        'total_land_acre': 5.0, 'latitude': 18.8530, 'longitude': 77.3240,
        'crop_name': 'Soybean', 'variety': 'Phule Agaon', 'crop_stage': 'post_harvest', 'crop_stage_days': 115,
        'demo_date': date(2025, 10, 2), 'product_name': 'Omega',
        'dose': 200, 'dose_unit': 'ml/acre',
        'demo_result': 'poor', 'demo_phase': 'completed',
        'additional_observations': 'Applied too late; crop already showing senescence',
        'remark': 'Timing was off — will retry pre-flowering next cycle',
    },
    {
        'local_id': 'demo-seed-8800000018',
        'farmer_name': 'Ramkrishna More', 'mobile_number': '8800000018',
        'village_name': 'Biloli', 'block_name': 'Biloli', 'district_name': 'Nanded',
        'total_land_acre': 7.0, 'latitude': 18.7650, 'longitude': 77.7300,
        'crop_name': 'Chilli', 'variety': 'Warangal Chapata', 'crop_stage': 'seedling', 'crop_stage_days': 15,
        'demo_date': date(2026, 1, 25), 'product_name': 'FPS Tara',
        'dose': 300, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Damping off prevented; good establishment',
        'remark': 'Applied as drench at transplanting',
    },
    {
        'local_id': 'demo-seed-8800000019',
        'farmer_name': 'Pramila Jagtap', 'mobile_number': '8800000019',
        'village_name': 'Kandhar', 'block_name': 'Kandhar', 'district_name': 'Nanded',
        'total_land_acre': 8.5, 'latitude': 18.2720, 'longitude': 77.5220,
        'crop_name': 'Turmeric', 'variety': 'Salem', 'crop_stage': 'vegetative', 'crop_stage_days': 70,
        'demo_date': date(2025, 9, 8), 'product_name': 'FPS Quat',
        'dose': 400, 'dose_unit': 'ml/acre',
        'demo_result': 'excellent', 'demo_phase': 'completed',
        'additional_observations': 'Rhizome rot incidence near zero on demo plot',
        'remark': 'Control plot had 30% incidence',
    },
    {
        'local_id': 'demo-seed-8800000020',
        'farmer_name': 'Narayan Desai', 'mobile_number': '8800000020',
        'village_name': 'Loha', 'block_name': 'Loha', 'district_name': 'Nanded',
        'total_land_acre': 9.0, 'latitude': 18.0730, 'longitude': 77.0990,
        'crop_name': 'Cotton', 'variety': 'Mahyco MRC 6918', 'crop_stage': 'fruiting', 'crop_stage_days': 92,
        'demo_date': date(2025, 10, 18), 'product_name': 'Trident',
        'dose': 250, 'dose_unit': 'ml/acre',
        'demo_result': 'good', 'demo_phase': 'completed',
        'additional_observations': 'Mite population controlled, no phytotoxicity',
        'remark': 'Farmer appreciated quick knockdown',
    },
]


class Command(BaseCommand):
    help = 'Seed 20 product demo entries for testing'

    def handle(self, *args, **options):
        exec_user = User.objects.filter(is_superuser=True).first()
        if not exec_user:
            self.stdout.write(self.style.ERROR('No superuser found. Run createsuperuser first.'))
            return

        created = skipped = 0
        for d in DEMO_DATA:
            defaults = {
                'farmer_name':            d['farmer_name'],
                'mobile_number':          d['mobile_number'],
                'village_name':           d['village_name'],
                'block_name':             d['block_name'],
                'district_name':          d['district_name'],
                'total_land_acre':        d['total_land_acre'],
                'latitude':               d['latitude'],
                'longitude':              d['longitude'],
                'location':               Point(d['longitude'], d['latitude']),
                'crop_name':              d['crop_name'],
                'variety':                d['variety'],
                'crop_stage':             d['crop_stage'],
                'crop_stage_days':        d['crop_stage_days'],
                'demo_date':              d['demo_date'],
                'product_name':           d['product_name'],
                'dose':                   d['dose'],
                'dose_unit':              d['dose_unit'],
                'demo_result':            d['demo_result'],
                'demo_phase':             d['demo_phase'],
                'additional_observations': d['additional_observations'],
                'remark':                 d['remark'],
                'is_synced':              True,
                'approval_status':        'draft',
            }
            _, is_new = ProductDemo.objects.get_or_create(
                executive=exec_user,
                local_id=d['local_id'],
                defaults=defaults,
            )
            if is_new:
                created += 1
            else:
                skipped += 1

        self.stdout.write(self.style.SUCCESS(f'Product demos — Created: {created}, Skipped: {skipped}'))
