# Generated by Django 6.0.5 on 2026-05-26 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mandis',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MandiArrival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity', models.CharField(default='Chili', max_length=50)),
                ('date', models.DateField()),
                ('arrival_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in Quintal', max_digits=10)),
                ('avg_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Average rate in ₹ per Quintal', max_digits=10, null=True)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(choices=[('trader', 'Trader'), ('farmer', 'Farmer'), ('official', 'Mandi Official')], default='trader', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('mandi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='mandi.mandi')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandi_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('mandi', 'date', 'commodity')},
            },
        ),
    ]
