# Generated by Django 5.1.15 on 2026-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandiarrival',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('resubmitted', 'Resubmitted')], db_index=True, default='draft', max_length=30),
        ),
    ]
