# Generated by Django 6.0.5 on 2026-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandi', '0004_replace_mandi_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandiarrival',
            name='custom_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mandiarrival',
            name='source',
            field=models.CharField(choices=[('trader', 'Trader'), ('farmer', 'Farmer'), ('official', 'Mandi Official'), ('other', 'Other')], default='trader', max_length=20),
        ),
    ]
