# Generated by Django 6.0.5 on 2026-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandi', '0007_mandi_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandiarrival',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
