"""
Django settings for fps_backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Fail fast in production if SECRET_KEY is missing — never boot with a None or
# guessable key. A throwaway key is allowed ONLY in local DEBUG runs.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable must be set in production.')

# ALLOWED_HOSTS: explicit in production (no wildcard). Wildcard is permitted only
# under DEBUG for local development convenience.
_allowed = os.getenv('ALLOWED_HOSTS', '').strip()
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    raise ImproperlyConfigured('ALLOWED_HOSTS environment variable must be set in production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'django.contrib.gis',
    'django.contrib.postgres',  # ArrayField / GIN indexes for RBAC models
    'rest_framework',
    'corsheaders',
    'django_filters',
    'cloudinary_storage',  # durable media (photo) storage — see MEDIA config below
    'cloudinary',
    'simple_history',  # model history (RBAC audit foundation — wired to models in Phase 4)
    'django_celery_beat',  # DB-backed periodic task scheduler for Celery
    'rest_framework_simplejwt.token_blacklist',  # refresh-token revocation / force-logout

    # Phase 8: OpenAPI schema generation
    'drf_spectacular',

    # FPS apps — order matters: accounts first (custom user model)
    'accounts',
    'crops',
    'mandi',
    'product_demo',
    'admin_portal',
    'geo',
    'workflow',  # RBAC approval workflow (maker-checker state machine)
    'audit',     # RBAC immutable audit trail
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Phase 2: attaches _fps_request_id + _fps_actor_ip + _fps_actor_device to
    # every request for audit context.
    'accounts.middleware.AuditContextMiddleware',
    # Phase 4: records the request user on django-simple-history snapshots.
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fps_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fps_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_url = os.getenv('DATABASE_URL')
if _db_url:
    # conn_max_age keeps connections alive across requests (avoids reopening a
    # Postgres connection on every request — important on managed DBs like Neon).
    DATABASES = {'default': dj_database_url.parse(_db_url, conn_max_age=600)}
    # Override engine — dj_database_url sets postgresql; we need postgis for GeoDjango
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': os.getenv('DB_NAME', 'fps_db'),
            'USER': os.getenv('DB_USER', 'fps_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    # Phase 8: brute-force / DoS protection on all endpoints.
    # Login endpoint uses a tighter LoginRateThrottle (5/min per IP).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '300/minute',
        'login': '5/minute',    # applied via LoginRateThrottle on login views
    },
    # Phase 8: OpenAPI schema class for drf-spectacular.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ---------------------------------------------------------------------------
# Phase 8 — drf-spectacular (Swagger / OpenAPI 3.0)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Farm Prosperity System API',
    'DESCRIPTION': (
        'FPS backend API. Mobile field-executive endpoints are under /api/. '
        'Admin portal endpoints are under /api/admin/ and require a JWT issued '
        'by POST /api/admin/auth/login/ (aud: fps-admin).'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': True,
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded crop / demo / visit photos)
# ---------------------------------------------------------------------------
# Render's container disk is EPHEMERAL — anything written to the local
# filesystem is deleted on every redeploy/restart. So in production we store
# uploaded photos in Cloudinary (durable, free tier): when CLOUDINARY_URL is
# set, Django routes all ImageField/FileField writes there automatically.
# Without it (local dev), uploads fall back to the local filesystem.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

_media_backend = (
    'cloudinary_storage.storage.MediaCloudinaryStorage'
    if os.getenv('CLOUDINARY_URL')
    else 'django.core.files.storage.FileSystemStorage'
)
STORAGES = {
    'default': {'BACKEND': _media_backend},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# CORS — allow any origin only in local dev. In production, restrict to the
# explicit origins listed in CORS_ALLOWED_ORIGINS (comma-separated env var),
# e.g. the admin-portal domain. The mobile app is native (no browser Origin),
# so it is unaffected by CORS.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]
    # Optional regex origins (comma-separated), e.g. Vercel preview deploys.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r.strip()
        for r in os.getenv('CORS_ALLOWED_ORIGIN_REGEXES', '').split(',')
        if r.strip()
    ]

# ---------------------------------------------------------------------------
# Production security (proxy-aware). Render terminates TLS at its edge proxy and
# forwards X-Forwarded-Proto, so Django must trust that header to know the
# request was HTTPS. All hardening is gated on `not DEBUG` so local dev over
# plain HTTP is unaffected.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model — must be set before first migration
AUTH_USER_MODEL = 'accounts.User'

# JWT token settings
from datetime import timedelta
SIMPLE_JWT = {
    # 12h access lifetime is the established project setting (RBAC docs suggest 8h
    # for field use; we keep 12h deliberately — see docs/rbac/11-IMPLEMENTATION-PHASES.md).
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    # Blacklist rotated refresh tokens so revocation / force-logout actually invalidates
    # them (requires the token_blacklist app, added in INSTALLED_APPS above).
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ---------------------------------------------------------------------------
# Redis Django cache — Phase 2 Permission Engine.
# Uses DB 1 to keep the cache namespace separate from Celery's broker (DB 0).
# django-redis is already in requirements.txt (installed in Phase 0).
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Connection pool settings tuned for a small deployment.
            'CONNECTION_POOL_KWARGS': {'max_connections': 20},
            # Silently ignore Redis connection errors so a Redis outage
            # degrades gracefully to DB lookups rather than a 500.
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'fps',
        'TIMEOUT': 300,  # default TTL matches PermissionService.CACHE_TTL
    }
}

# ---------------------------------------------------------------------------
# Celery — async task layer (RBAC prerequisite). Broker/result backend are Redis.
# In local dev the Redis container from docker-compose.yml serves these.
from celery.schedules import crontab  # noqa: E402

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# Retain connection-retry-on-startup behavior (default flips in Celery 6).
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Phase 3: check for overdue approval instances every hour and escalate them.
# Phase 8: additional monitoring tasks.
CELERY_BEAT_SCHEDULE = {
    'check-approval-escalations': {
        'task': 'workflow.check_approval_escalations',
        'schedule': crontab(minute='0'),  # top of every hour
    },
    # Phase 8: alert admins about escalated approvals not actioned in 24h.
    'notify-unactioned-escalations': {
        'task': 'workflow.notify_unactioned_escalations',
        'schedule': crontab(minute='*/30'),  # every 30 minutes
    },
    # Phase 8: alert about field executives whose devices haven't synced in 48h.
    'check-sync-staleness': {
        'task': 'audit.check_sync_staleness',
        'schedule': crontab(minute='0', hour='*/6'),  # every 6 hours
    },
}

# ---------------------------------------------------------------------------
# Phase 4 — Audit Engine
# Set to False in test settings to disable async audit dispatch entirely
# (avoids Celery dependency in unit tests).
AUDIT_ENGINE_ENABLED = True
