# Generated by Django 6.0.5 on 2026-05-26 10:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CropEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(default='Chili', max_length=50)),
                ('area_this_year', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area_last_year', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('crop_stage', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post Harvest')], max_length=20)),
                ('crop_condition', models.CharField(choices=[('good', 'Good (70–100%)'), ('average', 'Average (40–69%)'), ('poor', 'Poor (0–39%)')], max_length=10)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Quintal per Acre', max_digits=8, null=True)),
                ('buyer_interest', models.BooleanField(null=True)),
                ('problem_pest', models.BooleanField(default=False)),
                ('problem_disease', models.BooleanField(default=False)),
                ('problem_weather', models.BooleanField(default=False)),
                ('problem_price_concern', models.BooleanField(default=False)),
                ('problem_other', models.CharField(blank=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('visit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Entry',
                'verbose_name_plural': 'Crop Entries',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='CropPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='crop_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crop_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crops.cropentry')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='crops.village')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cropentry',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_entries', to='crops.farmer'),
        ),
    ]
