# Generated by Django 6.0.5 on 2026-05-30 18:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Crop Master',
                'verbose_name_plural': 'Crop Masters',
                'ordering': ['crop_name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('village_name', models.CharField(max_length=200)),
                ('block_name', models.CharField(max_length=200)),
                ('district_name', models.CharField(max_length=200)),
                ('total_land_acre', models.DecimalField(decimal_places=4, max_digits=8)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('is_synced', models.BooleanField(default=True)),
                ('executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Visit',
                'verbose_name_plural': 'Farmer Visits',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CropRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('date_of_sowing', models.DateField()),
                ('current_area_acre', models.DecimalField(decimal_places=4, max_digits=8)),
                ('last_year_area_acre', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('this_year_area_acre', models.DecimalField(decimal_places=4, max_digits=8)),
                ('crop_stage', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post Harvest')], max_length=20)),
                ('crop_condition', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10)),
                ('problems', models.JSONField(default=list)),
                ('other_problem_detail', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops.farmervisit')),
            ],
            options={
                'verbose_name': 'Crop Record',
                'verbose_name_plural': 'Crop Records',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='visit_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crops.farmervisit')),
            ],
            options={
                'verbose_name': 'Visit Photo',
                'verbose_name_plural': 'Visit Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.cropmaster')),
            ],
            options={
                'verbose_name': 'Crop Variety',
                'verbose_name_plural': 'Crop Varieties',
                'ordering': ['variety_name'],
                'unique_together': {('crop', 'variety_name')},
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='crops.district')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['district__name', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
    ]
