# Generated by Django 6.0.5 on 2026-06-08 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_monitoring_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='crops.block')),
            ],
            options={
                'verbose_name': 'Village Master',
                'verbose_name_plural': 'Village Masters',
                'ordering': ['block__district__name', 'block__name', 'name'],
                'unique_together': {('name', 'block')},
            },
        ),
    ]
