# Generated by Django 5.1.15 on 2026-06-12 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_farmervisit_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='farmervisit',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id', ''), _negated=True), fields=('executive', 'local_id'), name='uniq_farmervisit_executive_local_id'),
        ),
    ]
