# Generated by Django 6.0.5 on 2026-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_farmervisit_uniq_farmervisit_executive_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmervisit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
