# Generated by Django 6.0.5 on 2026-06-25 18:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('trigger_condition', models.JSONField(blank=True, default=dict)),
                ('require_all', models.BooleanField(default=False)),
                ('approver_role_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('escalation_hours', models.IntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_approvalworkflow',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('resubmitted', 'Resubmitted'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('revision_count', models.SmallIntegerField(default=0)),
                ('revision_note', models.TextField(blank=True, default='')),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approvals', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.approvalworkflow')),
            ],
            options={
                'db_table': 'workflow_approvalinstance',
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('started_review', 'Started Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requested_revision', 'Requested Revision'), ('resubmitted', 'Resubmitted'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled'), ('commented', 'Commented')], max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow.approvalinstance')),
            ],
            options={
                'db_table': 'workflow_approvalaction',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['instance'], name='idx_apaction_instance'), models.Index(fields=['actor'], name='idx_apaction_actor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'started_review', 'approved', 'rejected', 'requested_revision', 'resubmitted', 'escalated', 'cancelled', 'commented'])), name='ck_approvalaction_action')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status'], name='idx_approval_status'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['submitted_by'], name='idx_approval_submitter'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_approval_object'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(condition=models.Q(('status__in', ['submitted', 'under_review'])), fields=['current_approver'], name='idx_approval_approver'),
        ),
        migrations.AddConstraint(
            model_name='approvalinstance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'under_review', 'approved', 'rejected', 'revision_requested', 'resubmitted', 'escalated', 'cancelled'])), name='ck_approvalinstance_status'),
        ),
    ]
