# Generated by Django 6.0.5 on 2026-06-25 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_username', models.CharField(max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=100)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_device', models.CharField(blank=True, default='', max_length=200)),
                ('event_type', models.CharField(max_length=50)),
                ('module', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('sync_batch_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor'], name='idx_audit_actor'), models.Index(fields=['event_type'], name='idx_audit_event'), models.Index(fields=['content_type', 'object_id'], name='idx_audit_object'), models.Index(fields=['-created_at'], name='idx_audit_created'), models.Index(fields=['module'], name='idx_audit_module')],
            },
        ),
    ]
